"""Shared camera and preview timing configuration."""

from __future__ import annotations

CAMERA_INDEX = 0
CAMERA_CANDIDATE_COUNT = 4
CAMERA_FRAME_WIDTH = 640
CAMERA_FRAME_HEIGHT = 480
CAMERA_MODE_DIGIT = "digit"
CAMERA_MODE_BOARD = "board"
CAMERA_MODE_HAND_COUNT = "hand_count"
CAMERA_BOARD_FRAME_WIDTH = 1280
CAMERA_BOARD_FRAME_HEIGHT = 720
CAMERA_WARMUP_FRAMES = 3
CAMERA_BUFFER_SIZE = 1
CAMERA_TARGET_FPS = 30.0
CAMERA_PREVIEW_INTERVAL_MS = 33
CAMERA_INFERENCE_INTERVAL_MS = 200
CAMERA_BOARD_INFERENCE_INTERVAL_MS = 700
CAMERA_HAND_INFERENCE_INTERVAL_MS = 120
CAMERA_WORKER_IDLE_MS = 10
CAMERA_CAPTURE_RETRY_MS = 40
CAMERA_THREAD_JOIN_TIMEOUT_MS = 800
CAMERA_MAX_PREVIEW_SIZE = 512
CAMERA_MAX_OCR_SIZE = 320
CAMERA_BOARD_MAX_OCR_SIZE = 960
CAMERA_STARTUP_GRACE_MS = 600
CAMERA_RESULT_HOLD_SECONDS = 0.8
CAMERA_EMPTY_RESET_FRAMES = max(1, int(round((CAMERA_RESULT_HOLD_SECONDS * 1000.0) / CAMERA_INFERENCE_INTERVAL_MS)))
CAMERA_SEQUENCE_HISTORY = 6
CAMERA_STABLE_MIN_COUNT = 2
CAMERA_TRACK_SMOOTHING = 0.45
CAMERA_TRACK_MAX_MISSES = 3
CAMERA_TRACK_MAX_DISTANCE_RATIO = 0.65
CAMERA_TRACK_DISTANCE_PENALTY = 0.18
CAMERA_TRACK_SAME_DIGIT_BONUS = 0.15
CAMERA_MATCH_MIN_IOU = 0.18
CAMERA_SIGNATURE_GRID = 10
CAMERA_OVERLAY_MAX_FRAME_LAG = 2
CAMERA_OVERLAY_MAX_AGE_SECONDS = CAMERA_RESULT_HOLD_SECONDS
CAMERA_ROI_WIDTH_RATIO = 0.55
CAMERA_ROI_HEIGHT_RATIO = 0.40
CAMERA_ROI_MIN_FOREGROUND_RATIO = 0.006
CAMERA_HAND_MAX_HANDS = 2
CAMERA_HAND_MODEL_COMPLEXITY = 1
CAMERA_HAND_MIN_DETECTION_CONFIDENCE = 0.50
CAMERA_HAND_MIN_TRACKING_CONFIDENCE = 0.50
CAMERA_HAND_STABLE_HISTORY = 5
CAMERA_HAND_STABLE_MIN_COUNT = 3
CAMERA_HAND_UNKNOWN_HOLD_SECONDS = 0.45
CAMERA_HAND_EMPTY_RESET_FRAMES = max(
    1,
    int(round((CAMERA_HAND_UNKNOWN_HOLD_SECONDS * 1000.0) / CAMERA_HAND_INFERENCE_INTERVAL_MS)),
)
CAMERA_FAST_WORKER_COUNT = 2
CAMERA_FAST_WORKER_THREADS = 4
CAMERA_FALLBACK_WORKER_THREADS = 6
CAMERA_FAST_MAX_CANDIDATES = 6
CAMERA_FALLBACK_INTERVAL_MS = 1800
CAMERA_FAST_MIN_BOX_AREA_RATIO = 0.01
CAMERA_FAST_MIN_BOX_HEIGHT_RATIO = 0.18
CAMERA_FAST_MIN_REVIEW_SCORE = 0.70
CAMERA_MIN_CONFIDENCE = 0.50
CAMERA_MIN_AVERAGE_CONFIDENCE = 0.45
CAMERA_BOARD_MIN_AREA_RATIO = 0.20
CAMERA_BOARD_POLYGON_SMOOTHING = 0.35
CAMERA_BOARD_BLUR_THRESHOLD = 80.0
CAMERA_BOARD_CHANGE_THRESHOLD = 0.03
CAMERA_BOARD_SHIFT_THRESHOLD_RATIO = 0.02
CAMERA_BOARD_STABILITY_IOU = 0.60
CAMERA_BOARD_CANNY_LOW = 50
CAMERA_BOARD_CANNY_HIGH = 150
